### PR TITLE
Kole - Announcements F1

### LINKED ISSUE #21: Epic Issue F1: fixtures/components for announcements
Frontend Issue 1 of #1

Developer Story:

* As an developer
* I have access to fixtures, components and storybook stories for a form and table for Announcements
* So that I can build future features for the Announcements table

Acceptance Criteria:

- [x] There is a form component for announcements suitable for crud operations (similar to team03 form components, but with a nice large textarea for the announcement text.)  Note that the commonsId is not part of the form; it will be set implicitly.
- [x] There is a table component for announcements (similar to team03 table components)  Note that the commonsId is not part of the table component; it will be the same for all entries in the table, so we will put it at the top of the page separately.
- [x] There are fixtures that match the format of the GET operations for the API endpoints being worked on in the second issue.  Note that the fixtures should be organized so that each set of announcements is for a single commons, since we only ever work with the announcements for one commons at at time, even though in the database they are all stored in the same database able.
- [x] There are storybook entries for the form and table components.   Note that the storybook entries for the table should focus on one commons at a time (see discussion above under fixtures).

### PR DESCRIPTION
**Pull request by ktkikuta**
## Overview

In this PR, I created the form and table components for the announcements feature, as well as the fixtures and stories for both.

## Tests

- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #21

### CODE REVIEW

**Review by hyi96 — CHANGES_REQUESTED** [review]
I think the first acceptance criterion requires a "textarea" (a specific html input type) for the announcement text in AnnouncementsForm.  

also storybook gives me error when trying to view Three Items Ordinary User and Three Items Admin User of the AnnouncementsTable component.
image

**Comment by ktkikuta** [comment]
Changed Announcements type to textarea, good catch.

I got that storybook error too, but I closed the error and never saw it again. All my stories seem to work

**Review by hyi96 — CHANGES_REQUESTED** [review]
i can see the storybook without error now but i don't think the textarea part is changed. i am still seeing a regular text input. maybe checkout the example here https://getbootstrap.com/docs/5.0/forms/form-control/

**Comment by ktkikuta** [comment]
Announcement is now a textarea 3 rows tall

**Review by hyi96 — APPROVED** [review]
LGTM

**Review by sangitakunapuli — APPROVED** [review]
LGTM

**Pull request merged**
