### PR TITLE
Hl epic chat effective backend

### LINKED ISSUE #26: EPIC: Admin can turn chat on/off (2): effective backend
### Description
A PR to make the backend endpoints respect the value of the field, meaning they will respond for regular users if/only if the showChat field is true, and return 403 if the field is false, but admins get responses no matter what the value of the field is. You won't be able to test interactively, but you can write unit tests that will manually set up a commons where showChat is false for purposes of the unit test. Again, at this point, no users facing functionality has changed, since there is no interactive way to set the chat field either through the backend or the frontend.

### Prerequisites
- [x] https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-4/pull/31 has been merged into EPIC-CHAT-ON-OFF-MAIN
- [x] create a new branch from EPIC-CHAT-ON-OFF-MAIN

### Acceptance Criteria
- [ ] For admins, all endpoints of ChatMessageController always respond no matter what the value of showChat is.
- [ ] For users, get and post endpoints of ChatMessageController return 403 if showChat is false. 
- [ ] backend unit tests for the previous 2 criteria. 
- [ ] PR for merging into EPIC-CHAT-ON-OFF-MAIN.

### PR DESCRIPTION
**Pull request by hongye-liang**
## Overview

In this PR, I created a variable named showChat to check the status of the user. If the user is not an admin and has set the showchat to false then it will return a 403 when the user ties to use the chat.

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #26

### CODE REVIEW

**Review by hyi96 — CHANGES_REQUESTED** [review]
Hi Hongye, this pr should request to be merged into EPIC-CHAT-ON-OFF-MAIN. Did you create this branch from main or EPIC-CHAT-ON-OFF-MAIN?

**Review by hyi96 — CHANGES_REQUESTED** [review]
I am getting error when trying to use chat as a regular user in a commons where showChat is true. 
image

**Comment by hyi96** [comment]
I can take over this issue/branch if you are working on (5). @hongye-liang

**Comment by hongye-liang** [comment]
@hyi96 OK sounds good. I don't know why I can't log in using local host, it keeps me in the log in page. I will work on (5).

**Pull request closed without merging**
