### PR TITLE
AN - fixed whitespace for leaderboard table

### LINKED ISSUE #3: FEATURE: Fix whitespace in Leaderboard page
### Have you updated the title?

- [X] I have updated the issue's title.

### As a...

user

### I can...

view the leaderboard page without asymmetric whitespace

### So that...

I can have a better leaderboard UI

### Discussion

Currently the leaderboard page is left justified, and it has a lot of whitespace on the right side.

Screenshot 2024-02-21 at 5 17 36 PM

### Acceptance Criteria

- [ ] When an admin or user clicks on the leaderboard page, they should not see the right whitespace
- [ ] The table should be centered and have a better UI, so it is aesthetic and easy to navigate

### Implementation Todos

Frontend:
- [x] Change the formatting of the Leaderboard table
- [x] Feel free to change other UI aspects of the table to make it better

Testing:
- [x] Front end tests pass and there is adequate coverage

### PR DESCRIPTION
**Pull request by anguyen412**
## Overview

In this PR, the whitespace on the right of the leaderboard table is removed.

## Screenshots (Optional)

Screenshot 2024-02-27 172210

## Validation (Optional)

1. Download this branch.
2. Run the project.
3. Go to this page.
4. Test this function.

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #3

### CODE REVIEW

**Review by hyi96 — COMMENTED** [review]
I don't know if this issue specifically asks you to change the style of the leaderboard table only. By changing the style of the OurTable component, you are changing the style of many different tables throughout the app. But having a table fill the available horizontal space does look a lot nicer in general. 
For example, this is the profit table with and without your change:
<p float="left">
  
  
</p>

**Comment by anguyen412** [comment]
> I don't know if this issue specifically asks you to change the style of the leaderboard table only. By changing the style of the OurTable component, you are changing the style of many different tables throughout the app. But having a table fill the available horizontal space does look a lot nicer in general. For example, this is the profit table with and without your change:
> 
>  

I also only really wanted to change the style of the leaderboard table but the way the style is set up in the OurTable.js file makes it less flexible, if you know a way I can change it only in the leaderboard table I'd be happy to change it. But I don't think it's a big change either way.

**Review by hyi96 — APPROVED** [review]
I think this is fine. Let's see if one of the TAs approves.

**Review by AnikaArora — APPROVED** [review]
LGTM! Regarding your previous comments on this PR: as long as all the tables across the application still look good visually, you're good to go. Once you confirm that, feel free to merge!

**Pull request merged**
