### PR TITLE
Merging CHAT-ON-OFF epic issue into main

### LINKED ISSUE #4: EPIC: Admin can turn chat on/off (like turning leaderboard on/off)
Note: Please read through all the instructions on this epic - we do not expect you to complete all of it at once, and you should definitely split it into separate issues and PRs. Feel free to tackle as much as you can, in order as specified below.

# User Story

As an admin, I can turn chat on/off for a commons so that I have more control over game play.

# Discussion

The idea is that the commons currently has a "showLeaderboard" field that can be true or false.  We want a "showChat" field that works the same way.    If the field is true, then users can interact with the chat.  If it is false, only admins see the chat button (just like with the leaderboard).  When it is true, backend endpoints related to chat work for all users (on that commons).  When it is false, backend endpoints for the chat work only for admin users.

# Acceptance Criteria

- [x] (1) A PR that adds the fields to the entity with a default value of true (this preserves existing functionality, since at first it's just an extra field in the table, hanging out with a default value of true, that isn't being looked at in the code anywhere else.  Make sure that creating a new commons or editing an existing one still works.) #25

- [x] (2) A PR to make the backend endpoints respect the value of the field, meaning they will respond for regular users if/only if the showChat field is true, and return 403 if the field is false, but admins get responses no matter what the value of the field is.  You won't be able to test interactively, but you can write unit tests that will manually set up a commons where showChat is false for purposes of the unit test.  Again, at this point, no users facing functionality has changed, since there is no interactive way to set the chat field either through the backend or the frontend. #26

- [x] (3) A PR adding the ability to set the field to true or false when doing the POST and PUT operations on the backend for commons.  Now, as an admin, you can test interactively by using swagger to change the value (though you still can't do it via the normal user interface.) #27

- [x] (4) A PR to add the checkbox to the CommonsForm so that you can change the value of showChat with a checkbox similar to that for showLeaderboard. #28

- [x] (5) A PR to hide or display the chat button for a user depending on the value of showChat of a Commons. #32 

- [x] Bonus PR (optional): Anytime after (1), though it makes more sense after (3) or after (4), you can add the showChat field to the CommonsTable that admins use to see all of the data for a commons.   This is optional, because that table doesn't necessarily have to show everything; admins can click "Edit" if they want to see all of the fields for the commons. #29

- [x] Once the first 5 or 6 items have been reviewed and merged into EPIC-CHAT-ON-OFF-MAIN, make a PR to merge EPIC-CHAT-ON-OFF-MAIN into main.

### PR DESCRIPTION
**Pull request by hyi96**
Once #4 is fully complete, and all the PRs into EPIC-CHAT-ON-OFF-MAIN have been reviewed and merged, make this branch up to date with main and possibly resolve conflicts with main before approving this PR.

Hello, can a staff @sangitakunapuli assign points to #31 when approving this PR? #31 is the base branch for #41 #40 #36 #34 which all have been reviewed and approved by a staff or team member.

Specifically, #31 #41 #40 have not been assigned points.

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #4

### CODE REVIEW

**Comment by rmarangoly** [comment]
LGTM from reviewing other CHAT Branches

**Comment by hyi96** [comment]
just made this branch up to date with main. also tested locally that this branch merged with open PRs #40 and #41 can merge into main.

**Comment by rmarangoly** [comment]
LGTM

**Comment by rmarangoly** [comment]
LGTM

**Review by anguyen412 — DISMISSED** [review]
LGTM

**Review by anguyen412 — APPROVED** [review]

**Review by sangitakunapuli — APPROVED** [review]
LGTM

**Pull request merged**
