### PR TITLE
Kole - UX Faster image loading

### LINKED ISSUE #6: UX: Faster image loading
### Have you updated the title?

- [X] I have updated the issue's title.

### As a...

user

### I can...

see the background image load faster

### So that...

I am not annoyed when first loading the app

### Discussion

At the moment, the first time you load the app with an empty cache, the background image take a very long time to load.

This is a function of at least two things:
* The resolution of the images
* The compression used

You are encouraged to experiment with various image formats (.jpg, .png, .gif) to see which one gives the best tradeoff between how the image looks, and the load time.  Note that some image formats have "progressive display" where a lower res image is loaded first, and then progressively gets more clear.  That may be an option.

### Acceptance Criteria

- [x] Background images throughout the app load faster than before.

### Implementation Todos

This probably involves replacing the images in the assets folder, and possibly changing the embedded image names in some other files if the image type is changed.

### PR DESCRIPTION
**Pull request by ktkikuta**
## Overview

In this PR, I converted the background images for the home page from png file formats to jpg file formats for faster loading.

## Testing
PNG load time: 5.75 s
JPG load time: 1.28s

## Validation

1. Download this branch.
2. Run the project.
3. Go to home page.
4. Compare load time of background image from this instance and the example project.

## Tests

- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #6

### CODE REVIEW

**Comment by hyi96** [comment]
Is the comparison made between the production deployment and your personal development deployment? I think we need to make comparisons between actual server deployments. 
i deploy this branch to the qa deployment and compare it with production which is sync with main. This is indeed faster. I take the average of 5 loading times each. 
this branch (1.55 s): https://happycows-qa.dokku-04.cs.ucsb.edu/
main (2.32 s): https://happycows.dokku-04.cs.ucsb.edu/
roughly 33% faster. 
In terms of file sizes, the original PNG images are 5~6 times larger than the JPG images used here. 
I can't visually tell any resolution difference between the 2 sets of images, so I guess JPG is the superior format here.

**Review by hyi96 — DISMISSED** [review]
lgtm

**Review by AnikaArora — DISMISSED** [review]
LGTM!

**Review by anguyen412 — APPROVED** [review]
LGTM

**Review by AnikaArora — APPROVED** [review]
LGTM!

**Pull request merged**
