### PR TITLE
AN - B2 added controllers and tests for Announcements

### LINKED ISSUE #20: Epic Issue B2: Backend Controller for CRUD operations for announcements
Backend Issue 2 of #1
Should be started after finishing #19 

Developer Story:

* As an developer
* I have access to backend endpoints (through swagger) for CRUD operations for the Announcements table
* So that I can build future features using this table

Acceptance Criteria:

- [x] There is a POST endpoint to create new announcements
- [x] The POST endpoint to create new announcements rejects POST values with invalid data (e.g. a commonsId for a commons that doesn't exist, announcements with empty text, end date that is before start date, start date blank)
- [x] The POST endpoint allows end date to be blank, in which case it is stored as NULL in the database
- [x] There is a GET endpoint to get all announcements for a specified commons
- [x] There is a GET endpoint to get an announcement by its individual id number
- [x] There is a PUT endpoint that allows updating the announcement. It performs the same validations as the POST endpoing.
- [x] There is a DELETE endpoint that allows deleting an announcement

### PR DESCRIPTION
**Pull request by anguyen412**
## Overview

In this PR, I created controller for Annoucements and added tests.

## Screenshots (Optional)

Screenshot 2024-03-06 144542

## Validation (Optional)

1. Download this branch.
2. npm start
3. mvn spring-boot:run
4.  Log in, go to swagger
5.  Test endpoints and validations

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #20

### CODE REVIEW

**Review by hyi96 — CHANGES_REQUESTED** [review]
are regular users allowed to get announcement by id? i see that get all announcement is forbidden for regular users, but i can get all announcements by going through the id 1 by 1?

**Comment by anguyen412** [comment]
> are regular users allowed to get announcement by id? i see that get all announcement is forbidden for regular users, but i can get all announcements by going through the id 1 by 1?

The acceptance criteria isn't clear on what the privileges should be for admins/users, I'm honestly not sure what it should be

**Review by hyi96 — DISMISSED** [review]
well, let's see what @sangitakunapuli thinks about the privilege level of the get by id endpoint.

**Review by anguyen412 — COMMENTED** [review]
Updated get by id/get all to have the same permissions

**Review by hongye-liang — APPROVED** [review]
LGTM!

**Review by AnikaArora — APPROVED** [review]

**Pull request merged**
